### ISSUE TITLE
errors: osm_border_linestring*

### ISSUE THREAD

**Issue by jas-** [acalcutt/wdb-map-gen#6]
First, thanks for publishing the [article](https://www.techidiots.net/notes/mapbox-gl-tileserver-gl/create-an-open-map-tiles-map-without-docker) and second thanks for the automation effort with this set of scripts.

Been researching the trove of information about creating mbtiles and serving them to only find that this seems to be the only *real* guide to accomplishing the task.

Anyways, I am seeing some errors that i am not sure how to address:
```
====> : Start importing border data from http://openstreetmap.org into PostgreSQL 
NOTICE:  table "osm_border_linestring" does not exist, skipping
DROP TABLE
CREATE TABLE
CREATE INDEX
NOTICE:  table "osm_border_linestring_gen1" does not exist, skipping
DROP TABLE
NOTICE:  table "osm_border_linestring_gen2" does not exist, skipping
DROP TABLE
NOTICE:  table "osm_border_linestring_gen3" does not exist, skipping
DROP TABLE
NOTICE:  table "osm_border_linestring_gen4" does not exist, skipping
DROP TABLE
NOTICE:  table "osm_border_linestring_gen5" does not exist, skipping
DROP TABLE
NOTICE:  table "osm_border_linestring_gen6" does not exist, skipping
DROP TABLE
NOTICE:  table "osm_border_linestring_gen7" does not exist, skipping
DROP TABLE
NOTICE:  table "osm_border_linestring_gen8" does not exist, skipping
DROP TABLE
NOTICE:  table "osm_border_linestring_gen9" does not exist, skipping
DROP TABLE
NOTICE:  table "osm_border_linestring_gen10" does not exist, skipping
```
The `load_all.sh` does have the requisite script being called.

**Comment by acalcutt** [comment]
I think that is normal. In load_osmborder.sh there are lines (line 40-49) to delete those tables if they don't exist. Because this is the first run, those tables don't exist yet. that would be more for if the script was ran twice, it would delete and recreate those tables.

After those notices, do you see it creating and analyzing tables? when it analyzes the tables it should give back a row count. as long as those row counts are not zero the border import is most likely working.

**Comment by jas-** [comment]
Fixed. I had some dependencies causing issues.
